print("\nMenu:\n")
print("1. List all records")
print("2. Create record")
print("3. Delete record")
print("4. Edit record")
print("5. Show statistics")
print("_______________________")
print("[Choose number or Exit]")